module-template: ! 'module MODULE_NAME where

'
extensions:
  GeneralizedNewtypeDeriving: true
  TemplateHaskell: true
  OverloadedStrings: true
  GADTs: true
  ImplicitPrelude: false
  QuasiQuotes: true
  FlexibleInstances: true
  TypeFamilies: true
  CPP: true
  MultiParamTypeClasses: true
  PatternGuards: true
  FlexibleContexts: true
environment: ghc-7.4.2-stable-13.09
cabal-file: project.cabal
version: 1
extra-packages: ''
ghc-args:
- -Wall
- -Werror
excluded-modules: []
