module-template: ! 'module MODULE_NAME where

'
extensions:
  GeneralizedNewtypeDeriving: true
  TemplateHaskell: true
  OverloadedStrings: true
  GADTs: true
  ImplicitPrelude: false
  QuasiQuotes: true
  FlexibleInstances: true
  TypeFamilies: true
  CPP: true
  MultiParamTypeClasses: true
  PatternGuards: true
  FlexibleContexts: true
environment: default
cabal-file: project.cabal
version: 1
ghc-args: []
excluded-modules: []
