apiVersion: v1
kind: ReplicationController
metadata:
    name: yesodweb
    labels:
        name: yesodweb
spec:
  replicas: 1
  selector:
    name: yesodweb
  template:
    metadata:
        labels:
            name: yesodweb
    spec:
        containers:
        - name: yesodweb
          image: snoyberg/yesodweb
          imagePullPolicy: Always
          command: ["yesodweb", "development"]
          workingDir: /app
          ports:
          - containerPort: 3001
            hostPort: 3001
          env:
          - name: PORT
            value: "3001"
          livenessProbe:
              httpGet:
                  path: /
                  port: 3001
