apiVersion: v1
kind: Service
metadata:
    name: yesodweb
    labels:
        name: yesodweb
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
    selector:
        name: yesodweb
