stanzas:
    - type: webapp
      exec: ../dist/build/yesodweb/yesodweb
      args:
        - production
#      env:
#        CONTENT_REPO: /home/ubuntu/sites/yesodweb.com/content
      hosts:
        - www.yesodweb.com

    - type: static-files
      host: static.yesodweb.com
      root: ../static
      directory-listing: false

    - type: redirect
      hosts:
        - www.yesodweb.org
        - yesodweb.org
        - yesodweb.com
        - docs.yesodweb.com
      status: 301
      actions:
        - host: www.yesodweb.com
          port: 80

exec: ../dist/build/yesodweb/yesodweb
copy-to: ubuntu@www.yesodweb.com:/opt/keter/incoming
